model:
  - GIN
device:
  - cuda
batch_size:
  - 64
learning_rate:
  - 0.01
classifier_epochs:          
  - 200
hidden_units:
  - [128, 128, 128, 128, 128] 
optimizer:                 
  - Adam
scheduler:                 
  - null
loss:                        
  - MulticlassClassificationLoss
train_eps:
  - True
l2:                         
  - 0.0001
aggregation:
  - sum
gradient_clipping:         
  - null
dropout:
  - 0.5
early_stopper:            
  -
    class: Patience
    args:
      patience: 50
      use_loss: False
shuffle:                   
  - True
resume:                   
  - False